#https://medium.com/@adilsonbna/ansible-k8s-for-the-laziest-person-part-2-a0fea80c490c
---
- name: install dependencies
  apt:
   name:
     - python3
     - python3-yaml
     - openshift-imagebuilder
  become: yes 

    #ship pi-hole.yaml
    #kubectl create -f pi-hole.yaml
