---
- name: install dependencies for kubectl module
  apt:
   name:
     - python3
     - python3-yaml
     - openshift-imagebuilder
   state: present
  become: yes 

#TODO kubectl module exists in community, try it out
#instead of the manual action here
- name: ship pi-hole pod
  copy:
    src: files/pihole.yaml 
    dest: /home/mathieu/pihole.yaml

- name: create pi-hole pod
  shell: kubectl create -f pihole.yaml
  when: pihole_exists
